import React, { createContext, useContext, useEffect, useState } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

const STORAGE_KEY = 'aksha-lang';

// Idioma inicial: preferencia guardada > idioma del navegador > inglés.
const getInitialLang = () => {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored === 'en' || stored === 'es') return stored;
  } catch { /* localStorage puede no estar disponible (SSR/privacidad) */ }
  if (typeof navigator !== 'undefined' && (navigator.language || '').toLowerCase().startsWith('es')) {
    return 'es';
  }
  return 'en';
};

export const translations = {
  en: {
    nav: {
      home: 'Home',
      science: 'Science',
      sampleAnalysis: 'Sample Analysis',
      pricing: 'Pricing',
      discover: 'Discover',
      login: 'Login',
      getReport: 'Get Your Report',
      logout: 'Logout',
      dashboard: 'Dashboard',
      whyWeExist: 'Why We Exist',
    },
    home: {
      heroTitle: 'The Purpose of Your Life',
      heroSubtitle: 'While AI transforms everything, AKSHA LIFE reveals the one thing it cannot replace — who you uniquely are.',
      discoverBtn: 'Discover Your Purpose',
      scienceBtn: 'The Science Behind AKSHA LIFE',
      whatAkshaTitle: 'What AKSHA LIFE does for you',
      whatAkshaSubtitle: 'Neuroscience. Psychology. Archetypes. Chronobiology.\nAll synthesized around one person: you.',
      revealsTitle: 'Find Out Who You Really Are',
      revealsText: 'Most people spend years figuring out what they\'re naturally built for. You don\'t have to. AKSHA LIFE maps your unique strengths, energy and purpose — and gives you a clear action plan for what\'s next.',
      translatesTitle: 'Stop Guessing. Start Moving.',
      translatesText: 'What if you woke up Monday knowing exactly where to focus your energy? AKSHA LIFE gives you a personalized map of your natural strengths and purpose — so you stop guessing and start moving.',
      ctaTitle: 'Find Out Who',
      ctaHighlight: 'You Really Are',
      ctaSubtitle: 'Enter your birth date. Get a clear map of your natural talents, strengths and purpose.\nEvery discipline studies a part of you. AKSHA LIFE synthesizes them all.',
      ctaBtn: 'Get My Purpose Map',
      reviewsTitle: 'What people discovered about themselves',
    },
    common: {
      loading: 'Loading...',
    },
    footer: {
      tagline: 'Discover your Human Blueprint in an AI-driven world. AKSHA transforms birth data into insights about your Energy, Strengths, Gifts, and Impact.',
      explore: 'Explore',
      home: 'Home',
      science: 'The Science',
      sampleAnalysis: 'Sample Analysis',
      discover: 'Discover',
      contactLegal: 'Contact & Legal',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      rights: 'All rights reserved.',
      motto: 'Illuminating human potential in the digital age',
    },
    login: {
      metaTitle: 'Login - AKSHA',
      metaDesc: 'Login to your AKSHA account to access your purpose profile and career roadmap.',
      title: 'Welcome back',
      subtitle: 'Login to continue your purpose discovery journey',
      email: 'Email',
      emailPlaceholder: 'your@email.com',
      password: 'Password',
      passwordPlaceholder: 'Enter your password',
      submit: 'Login',
      submitting: 'Logging in...',
      noAccount: 'Don\'t have an account?',
      signupLink: 'Sign up',
      success: 'Login successful',
      invalidCredentials: 'Invalid email or password',
    },
    signup: {
      metaTitle: 'Sign Up - AKSHA',
      metaDesc: 'Create your AKSHA account and start discovering your unique purpose.',
      title: 'Create your account',
      subtitle: 'Start your journey to discover your unique purpose',
      name: 'Name',
      namePlaceholder: 'Your name',
      email: 'Email',
      emailPlaceholder: 'your@email.com',
      password: 'Password',
      passwordPlaceholder: 'At least 8 characters',
      confirmPassword: 'Confirm Password',
      confirmPlaceholder: 'Re-enter your password',
      submit: 'Sign Up',
      submitting: 'Creating account...',
      haveAccount: 'Already have an account?',
      loginLink: 'Login',
      success: 'Account created successfully',
      mismatch: 'Passwords do not match',
      tooShort: 'Password must be at least 8 characters',
      failed: 'Failed to create account',
    },
    paymentSuccess: {
      metaTitle: 'Payment Successful — AKSHA',
      metaDesc: 'Your payment was received. Your personalized AKSHA Purpose Map is on its way to your inbox.',
      confirmed: 'Payment confirmed',
      title: 'Your journey begins now',
      thanksBefore: 'Thank you for choosing the ',
      planReport: 'AKSHA {plan} Report',
      arrivalNote: 'Check your email — your Purpose Map will arrive within {minutes} minutes.',
      bullet1: 'Your report is being generated by AKSHA AI',
      bullet2: 'You\'ll receive a PDF to the email you provided',
      bullet3: 'Questions? Email us at purpose@aksha.life',
      startBtn: 'Start Your Discovery',
      homeBtn: 'Back to Home',
      planBasic: 'Basic',
      planPro: 'Pro',
    },
    dashboard: {
      metaTitle: 'Dashboard - AKSHA',
      metaDesc: 'View your purpose profile, career roadmap, and personalized insights.',
      title: 'Your Purpose Dashboard',
      subtitle: 'Track your journey and explore personalized insights',
      emptyTitle: 'No profiles yet',
      emptyText: 'Start your discovery journey to create your first purpose profile',
      emptyBtn: 'Discover Your Purpose',
      revealsTitle: 'What Your Map Reveals About You',
      revealsSubtitle: 'A comprehensive, highly personalized dossier detailing every facet of your innate potential.',
      roadmapTitle: 'Your Career Roadmap',
      savedTitle: 'Saved Profiles',
      created: 'Created',
      atTime: 'at',
      confirmDelete: 'Are you sure you want to delete this profile?',
      deleted: 'Profile deleted',
      deleteFailed: 'Failed to delete profile',
      loadFailed: 'Failed to load profiles',
      actionItems: 'Action Items',
      priority: { high: 'high', medium: 'medium', low: 'low' },
    },
    chat: {
      title: 'AI Chat',
      clear: 'Clear',
      loadingHistory: 'Loading history...',
      placeholder: 'Type a message...',
      send: 'Send',
      uploadImages: 'Upload images',
      generatedImageAlt: 'AI generated image',
    },
  },
  es: {
    nav: {
      home: 'Inicio',
      science: 'Ciencia',
      sampleAnalysis: 'Análisis de Muestra',
      pricing: 'Precios',
      discover: 'Descubrir',
      login: 'Entrar',
      getReport: 'Obtener mi Reporte',
      logout: 'Salir',
      dashboard: 'Panel',
      whyWeExist: 'Por Qué Existimos',
    },
    home: {
      heroTitle: 'El Propósito de Tu Vida',
      heroSubtitle: 'Mientras la IA transforma todo, AKSHA LIFE revela lo único que no puede reemplazar — quién eres tú de manera única.',
      discoverBtn: 'Descubre Tu Propósito',
      scienceBtn: 'La Ciencia detrás de AKSHA LIFE',
      whatAkshaTitle: 'Lo que AKSHA LIFE hace por ti',
      whatAkshaSubtitle: 'Neurociencia. Psicología. Arquetipos. Cronobiología.\nTodo sintetizado alrededor de una sola persona: tú.',
      revealsTitle: 'Descubre Quién Eres Realmente',
      revealsText: 'La mayoría de las personas pasan años intentando descubrir para qué están naturalmente hechas. Tú no tienes que hacerlo. AKSHA LIFE mapea tus fortalezas únicas, energía y propósito — y te da un plan de acción claro para lo que sigue.',
      translatesTitle: 'Deja de Adivinar. Empieza a Moverte.',
      translatesText: '¿Y si el lunes supieras exactamente dónde enfocar tu energía? AKSHA LIFE te da un mapa personalizado de tus fortalezas y propósito natural — para que dejes de adivinar y empieces a moverte.',
      ctaTitle: 'Descubre Quién',
      ctaHighlight: 'Eres Realmente',
      ctaSubtitle: 'Introduce tu fecha de nacimiento. Recibe un mapa claro de tus talentos naturales, fortalezas y propósito.\nCada disciplina estudia una parte de ti. AKSHA LIFE las sintetiza todas.',
      ctaBtn: 'Obtener Mi Mapa de Propósito',
      reviewsTitle: 'Lo que otros descubrieron sobre sí mismos',
    },
    common: {
      loading: 'Cargando...',
    },
    footer: {
      tagline: 'Descubre tu Mapa Humano en un mundo impulsado por la IA. AKSHA transforma tus datos de nacimiento en perspectivas sobre tu Energía, Fortalezas, Don e Impacto.',
      explore: 'Explorar',
      home: 'Inicio',
      science: 'La Ciencia',
      sampleAnalysis: 'Análisis de Muestra',
      discover: 'Descubrir',
      contactLegal: 'Contacto y Legal',
      privacy: 'Política de Privacidad',
      terms: 'Términos del Servicio',
      rights: 'Todos los derechos reservados.',
      motto: 'Iluminando el potencial humano en la era digital',
    },
    login: {
      metaTitle: 'Entrar - AKSHA',
      metaDesc: 'Entra a tu cuenta AKSHA para acceder a tu perfil de propósito y tu hoja de ruta profesional.',
      title: 'Bienvenido de nuevo',
      subtitle: 'Entra para continuar tu viaje de descubrimiento de propósito',
      email: 'Email',
      emailPlaceholder: 'tu@email.com',
      password: 'Contraseña',
      passwordPlaceholder: 'Introduce tu contraseña',
      submit: 'Entrar',
      submitting: 'Entrando...',
      noAccount: '¿No tienes una cuenta?',
      signupLink: 'Regístrate',
      success: 'Sesión iniciada correctamente',
      invalidCredentials: 'Email o contraseña inválidos',
    },
    signup: {
      metaTitle: 'Registro - AKSHA',
      metaDesc: 'Crea tu cuenta AKSHA y empieza a descubrir tu propósito único.',
      title: 'Crea tu cuenta',
      subtitle: 'Comienza tu viaje para descubrir tu propósito único',
      name: 'Nombre',
      namePlaceholder: 'Tu nombre',
      email: 'Email',
      emailPlaceholder: 'tu@email.com',
      password: 'Contraseña',
      passwordPlaceholder: 'Mínimo 8 caracteres',
      confirmPassword: 'Confirmar Contraseña',
      confirmPlaceholder: 'Vuelve a escribir tu contraseña',
      submit: 'Registrarme',
      submitting: 'Creando cuenta...',
      haveAccount: '¿Ya tienes una cuenta?',
      loginLink: 'Entrar',
      success: 'Cuenta creada correctamente',
      mismatch: 'Las contraseñas no coinciden',
      tooShort: 'La contraseña debe tener al menos 8 caracteres',
      failed: 'No se pudo crear la cuenta',
    },
    paymentSuccess: {
      metaTitle: 'Pago Exitoso — AKSHA',
      metaDesc: 'Tu pago fue recibido. Tu Mapa de Propósito AKSHA personalizado va en camino a tu correo.',
      confirmed: 'Pago confirmado',
      title: 'Tu viaje comienza ahora',
      thanksBefore: 'Gracias por elegir el ',
      planReport: 'Reporte AKSHA {plan}',
      arrivalNote: 'Revisa tu correo — tu Mapa de Propósito llegará en {minutes} minutos.',
      bullet1: 'Tu reporte está siendo generado por la IA de AKSHA',
      bullet2: 'Recibirás un PDF en el email que proporcionaste',
      bullet3: '¿Preguntas? Escríbenos a purpose@aksha.life',
      startBtn: 'Comenzar Mi Descubrimiento',
      homeBtn: 'Volver al Inicio',
      planBasic: 'Básico',
      planPro: 'Pro',
    },
    dashboard: {
      metaTitle: 'Panel - AKSHA',
      metaDesc: 'Consulta tu perfil de propósito, tu hoja de ruta profesional y tus perspectivas personalizadas.',
      title: 'Tu Panel de Propósito',
      subtitle: 'Sigue tu viaje y explora perspectivas personalizadas',
      emptyTitle: 'Aún no hay perfiles',
      emptyText: 'Comienza tu viaje de descubrimiento para crear tu primer perfil de propósito',
      emptyBtn: 'Descubre Tu Propósito',
      revealsTitle: 'Lo Que Tu Mapa Revela Sobre Ti',
      revealsSubtitle: 'Un dossier completo y altamente personalizado que detalla cada faceta de tu potencial innato.',
      roadmapTitle: 'Tu Hoja de Ruta Profesional',
      savedTitle: 'Perfiles Guardados',
      created: 'Creado el',
      atTime: 'a las',
      confirmDelete: '¿Seguro que quieres eliminar este perfil?',
      deleted: 'Perfil eliminado',
      deleteFailed: 'No se pudo eliminar el perfil',
      loadFailed: 'No se pudieron cargar los perfiles',
      actionItems: 'Acciones',
      priority: { high: 'alta', medium: 'media', low: 'baja' },
    },
    chat: {
      title: 'Chat IA',
      clear: 'Limpiar',
      loadingHistory: 'Cargando historial...',
      placeholder: 'Escribe un mensaje...',
      send: 'Enviar',
      uploadImages: 'Subir imágenes',
      generatedImageAlt: 'Imagen generada por IA',
    },
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(getInitialLang);
  const t = translations[lang];
  const toggleLang = () => setLang(prev => prev === 'en' ? 'es' : 'en');

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, lang);
    } catch { /* sin persistencia disponible */ }
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
