import React, { useEffect } from 'react';
import { Helmet } from 'react-helmet';
import { Link, useSearchParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import { CheckCircle, ArrowRight, Sparkles } from 'lucide-react';
import { Button } from '@/components/ui/button';

const PLANS = {
  basic: 'Basic',
  pro: 'Pro',
};

const PaymentSuccessPage = () => {
  const [searchParams] = useSearchParams();
  const plan = searchParams.get('plan') || 'basic';
  const planName = PLANS[plan] || 'Basic';

  return (
    <>
      <Helmet>
        <title>Payment Successful — AKSHA</title>
        <meta name="description" content="Your payment was received. Your personalized AKSHA Purpose Map is on its way to your inbox." />
        <meta name="robots" content="noindex, nofollow" />
      </Helmet>

      <div className="min-h-screen bg-background flex items-center justify-center px-4 py-20">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, type: 'spring' }}
          className="max-w-lg w-full text-center"
        >
          {/* Icon */}
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ duration: 0.5, delay: 0.2, type: 'spring', stiffness: 200 }}
            className="flex justify-center mb-8"
          >
            <div className="relative">
              <div className="w-24 h-24 rounded-full bg-primary/10 border-2 border-primary/30 flex items-center justify-center">
                <CheckCircle className="w-12 h-12 text-primary" />
              </div>
              <div className="absolute inset-0 rounded-full bg-primary/5 blur-xl" />
            </div>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.3 }}
          >
            <p className="text-xs font-semibold tracking-widest uppercase text-primary mb-4">
              Payment confirmed
            </p>
            <h1 className="text-4xl md:text-5xl font-bold text-foreground mb-4 leading-tight" style={{ letterSpacing: '-0.02em' }}>
              Your journey begins now
            </h1>
            <p className="text-lg text-muted-foreground mb-8 leading-relaxed">
              Thank you for choosing the AKSHA <strong className="text-foreground">{planName} Report</strong>.
              Check your email — your Purpose Map will arrive within{' '}
              {plan === 'pro' ? '60 minutes' : '30 minutes'}.
            </p>

            <div className="p-6 rounded-lg border border-border/50 bg-card/50 mb-8 text-left space-y-3">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary flex-shrink-0" />
                <p className="text-sm text-foreground/80">Your report is being generated by Gemini AI</p>
              </div>
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary flex-shrink-0" />
                <p className="text-sm text-foreground/80">You'll receive a PDF to the email you provided</p>
              </div>
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary flex-shrink-0" />
                <p className="text-sm text-foreground/80">Questions? Email us at hello@aksha.life</p>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link to="/discover">
                <Button size="lg" className="text-base px-8 py-6 transition-all duration-300 hover:shadow-[0_0_25px_rgba(200,168,75,0.3)] active:scale-[0.98]">
                  Start Your Discovery
                  <ArrowRight className="ml-2 w-4 h-4" />
                </Button>
              </Link>
              <Link to="/">
                <Button size="lg" variant="outline" className="text-base px-8 py-6 border-primary/40 text-primary hover:bg-primary/10 transition-all active:scale-[0.98]">
                  Back to Home
                </Button>
              </Link>
            </div>
          </motion.div>
        </motion.div>
      </div>
    </>
  );
};

export default PaymentSuccessPage;
