
import React from 'react';
import { Helmet } from 'react-helmet';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { motion } from 'framer-motion';
import { Heart, Briefcase, Map, Target, Compass, Sparkles } from 'lucide-react';

const SampleAnalysisPage = () => {
  const modules = [
    {
      title: 'Passion',
      icon: Heart,
      score: 87,
      description: 'Your innate drives and what brings you energy.',
      insight: 'You show a profound drive for synthesizing complex information into digestible narratives. Your energy peaks when facilitating understanding between disparate groups.'
    },
    {
      title: 'Profession',
      icon: Briefcase,
      score: 92,
      description: 'The practical skills and competencies you naturally excel at.',
      insight: 'Strong natural aptitude for systems thinking, strategic planning, and empathic leadership. You naturally grasp the macro-vision while maintaining the interpersonal dynamics of a team.'
    },
    {
      title: 'Vocation',
      icon: Map,
      score: 78,
      description: 'How the world perceives your value and what you can be paid for.',
      insight: 'The market highly values your ability to bridge the gap between technical execution and human-centric design. Roles requiring deep empathy paired with analytical skills are prime targets.'
    },
    {
      title: 'Mission',
      icon: Target,
      score: 85,
      description: 'Your broader impact and contribution to the world.',
      insight: 'Your overarching mission points toward elevating human consciousness through technology or design, ensuring that as systems become more automated, they remain fundamentally human.'
    }
  ];

  const recommendations = [
    {
      role: 'Ethical AI Strategist',
      match: '94%',
      description: 'Guiding organizations to implement technology that enhances rather than replaces human potential.',
    },
    {
      role: 'Organizational Architect',
      match: '89%',
      description: 'Designing company structures and cultures that prioritize human flourishing and systemic efficiency.',
    },
    {
      role: 'Human-Centered Design Lead',
      match: '85%',
      description: 'Leading product teams to create solutions that deeply resonate with psychological and emotional human needs.',
    }
  ];

  return (
    <>
      <Helmet>
        <title>Sample Purpose Profile - AKSHA</title>
        <meta name="description" content="View a sample AKSHA Purpose Profile to see how our AI-driven analysis reveals your unique path." />
      </Helmet>

      <div className="min-h-screen bg-background">
        <section className="py-16 md:py-24">
          <div className="container mx-auto px-4 sm:px-6 lg:px-8">
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="max-w-4xl mx-auto text-center mb-16"
            >
              <Badge variant="outline" className="mb-6 px-4 py-1.5 text-primary border-primary/30 bg-primary/5 uppercase tracking-wider font-semibold">
                Sample Profile
              </Badge>
              <h1 className="text-4xl md:text-5xl font-bold mb-6 leading-tight text-foreground" style={{ letterSpacing: '-0.02em' }}>
                Inside an AKSHA <span className="text-primary">Analysis</span>
              </h1>
              <p className="text-lg text-muted-foreground leading-relaxed">
                This is a generalized example of the profound, personalized insights generated by our engine. Your actual profile will be tailored entirely to your unique data inputs.
              </p>
            </motion.div>

            <div className="max-w-5xl mx-auto">
              <h2 className="text-2xl md:text-3xl font-bold mb-8 flex items-center gap-3">
                <Compass className="w-8 h-8 text-primary" />
                The 4 Modules of Purpose
              </h2>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mb-16">
                {modules.map((mod, index) => {
                  const Icon = mod.icon;
                  return (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, y: 20 }}
                      whileInView={{ opacity: 1, y: 0 }}
                      viewport={{ once: true }}
                      transition={{ duration: 0.5, delay: index * 0.1 }}
                    >
                      <Card className="h-full border-border/50 bg-card shadow-sm hover:border-primary/40 transition-colors">
                        <CardHeader className="pb-4">
                          <div className="flex justify-between items-start mb-4">
                            <div className="p-3 rounded-xl bg-primary/10 border border-primary/20">
                              <Icon className="w-6 h-6 text-primary" />
                            </div>
                            <div className="text-right">
                              <div className="text-3xl font-bold text-primary">{mod.score}%</div>
                              <div className="text-xs text-muted-foreground font-medium uppercase tracking-wider">IVA Match</div>
                            </div>
                          </div>
                          <CardTitle className="text-xl mb-1">{mod.title}</CardTitle>
                          <CardDescription className="text-sm">{mod.description}</CardDescription>
                        </CardHeader>
                        <CardContent>
                          <div className="p-4 rounded-lg bg-muted/50 border border-border/50">
                            <p className="text-sm text-foreground/90 leading-relaxed">
                              "{mod.insight}"
                            </p>
                          </div>
                        </CardContent>
                      </Card>
                    </motion.div>
                  );
                })}
              </div>

              <motion.div
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ duration: 0.6 }}
              >
                <h2 className="text-2xl md:text-3xl font-bold mb-8 flex items-center gap-3">
                  <Sparkles className="w-8 h-8 text-primary" />
                  Aligned Career Trajectories
                </h2>
                
                <div className="space-y-6">
                  {recommendations.map((rec, idx) => (
                    <Card key={idx} className="border-border/50 bg-card overflow-hidden">
                      <div className="flex flex-col sm:flex-row">
                        <div className="sm:w-32 bg-muted/30 p-6 flex flex-col justify-center items-center border-b sm:border-b-0 sm:border-r border-border/50">
                          <div className="text-2xl font-bold text-primary">{rec.match}</div>
                          <div className="text-xs text-muted-foreground uppercase tracking-wider font-semibold text-center mt-1">Alignment</div>
                        </div>
                        <div className="p-6 flex-1">
                          <h3 className="text-xl font-bold text-foreground mb-2">{rec.role}</h3>
                          <p className="text-muted-foreground leading-relaxed">{rec.description}</p>
                        </div>
                      </div>
                    </Card>
                  ))}
                </div>
              </motion.div>
            </div>
          </div>
        </section>
      </div>
    </>
  );
};

export default SampleAnalysisPage;
